### ISSUE TITLE
Mobile friendly version

### ISSUE THREAD

**Issue by merlinfuchs** [Magic-Bots/xenon#1]
Have a version of xenon that does not use embeds and is mobile friendly. It could be triggered with a separate prefix or with a -m on the end of each command.

https://gitlab.com/magicbots/xenon_pu/issues/24

**Comment by buthed010203** [comment]
Would definitely want to add this to the interval command as well

**Comment by merlinfuchs** [comment]
Do you have an idea how to do that?

**Comment by buthed010203** [comment]
Just dont send the replies in code block form

**Comment by buthed010203** [comment]
Or say react with (reaction) for a mobile version (reaction) being a phone or somethin

**Comment by merlinfuchs** [comment]
Before clicking the phone
![image](https://user-images.githubusercontent.com/33966852/46731927-46cb0c80-cc8c-11e8-9a43-211e79bef64b.png)

After clicking it
![image](https://user-images.githubusercontent.com/33966852/46731938-50ed0b00-cc8c-11e8-9722-36a1963f21c0.png)

**Comment by buthed010203** [comment]
I guess you could close this now...
