### ISSUE TITLE
x!template load

### ISSUE THREAD

**Issue by buthed010203** [Magic-Bots/xenon#10]
The body to the error provided is pretty basic as seen [here.](https://i.imgur.com/xhlRCPr.png) I feel it could use a few upgrades and should instead say something along the lines of `No template name specified, join the [support server](https://discord.gg/Ty3cpWb) in order to find a template!`

**Comment by merlinfuchs** [comment]
Not that easy to do, because the errors are managed globaly. But I will try to make them better understandable.
