### ISSUE TITLE
Filters for template submissions

### ISSUE THREAD

**Issue by ThatLifeofGames** [Magic-Bots/xenon#125]
Might help cut some of the shit submissions out by checking for things like random new roles, repeated role names, spammy descriptions etc.

**Comment by ThatLifeofGames** [comment]
_and if anyone wants to expand on the "etc" feel free to reply_

**Comment by ThatLifeofGames** [comment]
Could automatically deny anything that starts with x! or x? ([Example](https://chris.land/i/1581429489))

**Comment by withmask** [comment]
Descriptions limits ? as an example, minimum of three words in a description (or more idk)

**Comment by ThatLifeofGames** [comment]
There's already a minimum length, but you could check that there are actual spaces in it not just `asdasdasdasdagdfdsgfdsgdsfg` 😂
