### ISSUE TITLE
Build command does not work

### ISSUE THREAD

**Issue by sleeplesskyru** [Magic-Bots/xenon#127]
I use `x!build` and by the time I get to the second page, the reaction roles stop responding to input...

**Comment by merlinfuchs** [comment]
That's probably related to the message cache, so switching to on_raw_reaction add will fix it. 
This should also be done for all other reaction prompts because the message cache is very limited.

**Comment by merlinfuchs** [comment]
Increasing the message cache should work for now too.

**Comment by sleeplesskyru** [comment]
okay, thank you!
