### ISSUE TITLE
Wont load a Backup

### ISSUE THREAD

**Issue by LuciferMTV** [Magic-Bots/xenon#128]
![98EAC99B-FEF0-47BE-BFB2-ECFE9C16E4D6](https://user-images.githubusercontent.com/60532170/73586318-20c50f00-4471-11ea-9514-32c003f20c5e.png)
![DBCBAB24-3D8D-434F-9610-CD353DA34D4D](https://user-images.githubusercontent.com/60532170/73586319-20c50f00-4471-11ea-8320-d487440a8207.png)

**Comment by ThatLifeofGames** [comment]
This isn't for support, it's for bugs and suggestions.

You can solve this in the **support server** rather than opening an issue. The faq will help you there.
