### ISSUE TITLE
x!sync 

### ISSUE THREAD

**Issue by buthed010203** [Magic-Bots/xenon#16]
Since you can copy servers and also back them up, it only makes sense that you would be able to sync things such as bans, roles and nicknames... (Ofc this would have to be a premium thing and probably only update every 30 mins or so but it would be super cool)

**Comment by merlinfuchs** [comment]
Would you like to see this feature to work in both directions (between two guilds) or should be one the master and one the child guild?

**Comment by merlinfuchs** [comment]
I think a master/parent and child setup would make more sense.

**Comment by buthed010203** [comment]
Yeah the master thing works

**Comment by buthed010203** [comment]
You should make the ban sync work both ways tho (i will never give up on ban sync)

**Comment by buthed010203** [comment]
In terms of the command you could make it `x!sync <serverid> [type]` so you would use it such as `x!sync 12345 channels roles` that way you could chose what to sync.
