### ISSUE TITLE
save db space by checking for changes

### ISSUE THREAD

**Issue by phil-flip** [Magic-Bots/xenon#18]
**Is your feature request related to a problem? Please describe.**
Its more likyely for you and your servers :)

**Describe the solution you'd like**
would it possible that the bot checks for server changes (if the backup-intervall is active), that way you would save alot of disk space for the db.

**Describe alternatives you've considered**
maybe add it as an additional command to toggle it.

**Comment by phil-flip** [comment]
hope i could help out with the idea ^^

**Comment by merlinfuchs** [comment]
Yeah, thanks for your suggestion. I think I will implement something like that in the future! 👍

**Comment by phil-flip** [comment]
btw i noticed the bot doesnt backup the server in an interval anymore. is there vurrenty something broken?

also where are u from

**Comment by buthed010203** [comment]
Just use the interval command again, when the rewrite was finished and the bot updated it didn't carry over the backup interval.

**Comment by merlinfuchs** [comment]
Obsolete because of the bot keeps only one automated backup.
