### ISSUE TITLE
Add !perms flag to loading

### ISSUE THREAD

**Issue by merlinfuchs** [Magic-Bots/xenon#2]
When I load backups, I don’t always want to load permissions but I may want roles, there are also other times where I just want to update permissions so if that was a thing it would be really cool!

https://gitlab.com/magicbots/xenon_pu/issues/22

**Comment by merlinfuchs** [comment]
Do you mean overwrites?

**Comment by buthed010203** [comment]
I mean like channel perms
So all of the channels just have blank perms

**Comment by merlinfuchs** [comment]
eh ok

**Comment by buthed010203** [comment]
:p

**Comment by merlinfuchs** [comment]
Well I could implement #3 for roles (that's pretty easy), but not for channels (that's pretty hard).

I think that would solve your problem?

**Comment by buthed010203** [comment]
Yeah I guess?

**Comment by buthed010203** [comment]
With channels couldnt you compare the names somehow?

**Comment by merlinfuchs** [comment]
Yeah that would be possible, but isn't really accurate.

**Comment by merlinfuchs** [comment]
For example, it would leave #general untouched, because pretty much every guild has that channel ..

**Comment by buthed010203** [comment]
I mean its better than nothing right?

**Comment by merlinfuchs** [comment]
Not better than a system that is accurate but takes a little longer

**Comment by buthed010203** [comment]
Ah thats true

**Comment by buthed010203** [comment]
Im fine with it adding a second or two per channel even though my backup loading already takes 4 mins for me xD

**Comment by merlinfuchs** [comment]
Would be part of #3
