### ISSUE TITLE
Syntax Error

### ISSUE THREAD

**Issue by rivc** [Magic-Bots/xenon#23]
```
Traceback (most recent call last):
  File "launcher.py", line 6, in <module>
    from bot import Xenon
  File "/root/xenon/bot.py", line 18
    self.log.info(f"Loaded {len(self.cogs)} cogs")
                             ^
```
How i can fix this?, i use Python 3

**Comment by merlinfuchs** [comment]
You are probably using Python 3.5.x or lower.

![image](https://user-images.githubusercontent.com/33966852/50531282-9f7da900-0b07-11e9-98d3-fd36c2164cd9.png)

😉
