### ISSUE TITLE
Js branch

### ISSUE THREAD

**Issue by Hector6704** [Magic-Bots/xenon#25]
Make a js branch, in eris if possible please :heart:

**Comment by merlinfuchs** [comment]
Maybe @ThatLifeofGames wants to do it. I won't ...

**Comment by Hector6704** [comment]
Ok, it could be a good thing

**Comment by ThatLifeofGames** [comment]
If I did, it wouldn't be in eris as Im only familiar with discord.js. But currently I don't have the time and I can't particularly see the point myself, as the py branch works as it is.

**Comment by merlinfuchs** [comment]
Will probably never happen

**Comment by withmask** [comment]
I created that https://github.com/withmask/XenonJS
It currently only have backups,  i am planning to add more (at least what is in the setup) also don't blame me if the code is not "good" 👀
