### ISSUE TITLE
x!copyroles

### ISSUE THREAD

**Issue by ANTHONYxMARS** [Magic-Bots/xenon#26]
Don't know if it's possible, but I would really like the role copying command, some templates have too many channels and I just want to copy the roles.

**Comment by ThatLifeofGames** [comment]
It's possible but would be better to do as arguments for x?copy rather than a whole new command. However x?copy doesn't copy templates, so you are just asking to be able to load templates with just roles, which is a totally different feature.

**Comment by buthed010203** [comment]
Isnt this literally just x!backup load <id> roles? Its already a thing..

**Comment by merlinfuchs** [comment]
Well it's copy not load
