### ISSUE TITLE
Voice channel member limits don't load properly

### ISSUE THREAD

**Issue by buthed010203** [Magic-Bots/xenon#27]
Sometimes the bot wont properly load a backup of voice channel member limits (the limits are set properly in the original server).

https://cdn.discordapp.com/attachments/499259944508456976/532177497891143700/image0.png

**Comment by merlinfuchs** [comment]
I wasn't able to reproduce this.

**Comment by buthed010203** [comment]
Im still able to repro this, made a fresh backup with id: ujf2s4kzksrh5ex2 and loaded on pro tested with copy, same thing but happens less.
