### ISSUE TITLE
Getting this error when pip install

### ISSUE THREAD

**Issue by Dinip** [Magic-Bots/xenon#28]
Command "/usr/bin/python3.6 -u -c "import setuptools, tokenize;__file__='/tmp/pip-install-j_i5fcaq/psutil/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /tmp/pip-record-kxew9psx/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /tmp/pip-install-j_i5fcaq/psutil/

Version: Python 3.6.8

**Comment by merlinfuchs** [comment]
When do you get this error?

**Comment by Dinip** [comment]
like 2 hours ago but I think I fix it a few minutes ago by installing python3.6-dev!

**Comment by merlinfuchs** [comment]
I wanted to know which action caused that error.... :D

**Comment by Dinip** [comment]
oh I forgot to post on the issue but it is on the title, my bad xD
It was pip install -U -r requirements.txt
I had python 3.6.8 installed and it was giving that error so I searched on the internet and I also installed python3.6-dev and seems to be fixed

edit: I'm not a python regular user... I'm kinda new on this :)

**Comment by merlinfuchs** [comment]
Oh my mistake, didn't see it ...
Every Python 3.6 version should work, the differences are very small. Maybe you had an deprecated version of the setuptools and reinstalling python fixed that.
