### ISSUE TITLE
Template system redo ideas

### ISSUE THREAD

**Issue by ThatLifeofGames** [Magic-Bots/xenon#29]
At some point, the template system will be redone, feel free to **reply with ideas for the new template system** and they will (at some point) be added to the list below to be accepted/denied.
_If anything is missing from the list below please let me know and i'll update it._

### Suggested/Planned
- [Template guidelines](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-464468879)

### Done
- [Template approval channel](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-464468987)
- Template search command suggested [here](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-473348545) and [here](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-478363351)
- [Template load count](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-480831782)
- [Minimum description size](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-484625745)
- Further reactions added to template approval with pre-defined deny reasons.
- [Prompts for creating template](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-461959145), possibly make the current method and this new method [both work](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-462031432)

### Denied
- [Website template list](https://github.com/Magic-Bots/xenon/issues/29#issuecomment-461960462)

**Comment by cblastin** [comment]
Having the template command laid out better so users don't get their template named messed up with the description. So for example:

_**user:** x!template create
**xenon:** please type the backup id below.
**user:** backup id
**xenon:** what would you like the template name to be?
**user:** insert name
**xenon:** what would you like the template description to be?
**user:** insert description
**xenon:** preview to confirm
**user:** confirms_

**Comment by cblastin** [comment]
have the templates organized on the website in categories for better access instead of the discord channel because even with the search feature, it is hard to find the style of templates that you want sometimes

**Comment by merlinfuchs** [comment]
Your first suggestion basically describes the old command. I changed it to the current one because people didn't understand how to use it. 😅

A template list on the site will definitely come in the future.

**Comment by ThatLifeofGames** [comment]
You could make both of the methods work for creating a template.

**Comment by ThatLifeofGames** [comment]
It needs **template guidelines** saying that you can be blacklisted and banned for breaking them.

Currently, we get a lot of templates against the tos, so a **template approval** (before they go public) would also be good to have so they can be checked against the guidelines.

**Comment by ThatLifeofGames** [comment]
![image](https://user-images.githubusercontent.com/35865509/52914999-b39f8480-32c6-11e9-82e5-4771cd2becd0.png)
Could have a new channel for approving templates in this way (only visible to staff of course)

**Comment by merlinfuchs** [comment]
The template_list channel is obsolete anyways because it's hard to keep the messages synchronized to the database and it's hard to find a specific template.

**Comment by ThatLifeofGames** [comment]
Also, template list is a huge problem with sharding, maybe it could be done on the website (same with the approval thing, however approval inside discord would be best as it's convenient)

**Comment by withmask** [comment]
Maybe an info that displays how much channels and roles are in a template quit useful with the search feature

**Comment by buthed010203** [comment]
I would suggest a x!template search feature but honestly seems like more of a hastle than its worth + few people would use it

Listing on the website would be the way to go, it would allow you to add some basic systems for tagging templates and up/downvoting them.

**Comment by ThatLifeofGames** [comment]
Display the amount of times a template has been loaded (this is already recorded, but isn't displayed anywhere)

**Comment by ThatLifeofGames** [comment]
Have a minimum template description size (maybe 30 characters?) This should stop people sending templates to the approval with pointless descriptions.

**Comment by ThatLifeofGames** [comment]
Updated original message with a proper checklist, since this is isn't very organised.

**Comment by merlinfuchs** [comment]
Actually not done yet

**Comment by merlinfuchs** [comment]
The only thing missing is the Template Guidelines. It could be part of the [docs](https://docs.discord.club/xenon) and the bot would link to it when creating a template.
Do you want to write it @ThatLifeofGames ?

**Comment by ThatLifeofGames** [comment]
I don't think guidelines are worth doing, so i'l close this since everything else is done.
