### ISSUE TITLE
Backing up messages when doing interval backups

### ISSUE THREAD

**Issue by jakester620** [Magic-Bots/xenon#30]
There is an option to backup messages when doing manual backups, but no automatic backups set on an interval. This would be a good feature to implement.

**Comment by buthed010203** [comment]
I mean, it would be nice but it would also take so much space

**Comment by cblastin** [comment]
It wouldn't be any different than the person making the backup themselves. If it was spammy, I could understand but with the rate that the bot's growing, it's gonna be an issue that will be ran into a lot.

**Comment by merlinfuchs** [comment]
There actually is a difference. When you create backups manually, you can decide every time if you want messages saved. With the backup interval, you decide it one time and the bot will do it until you decide you don't want it anymore.
So there would be many backups with chatlog that aren't necessary.

I will think about it and maybe find a smarter way to implement it.

**Comment by jakester620** [comment]
Implement a shorter retention time for interval backups to counter the size
increase of messages. Keep the default still at 0. That would be my
suggestion for dealing with it.

**Comment by buthed010203** [comment]
Im thinking maybe add a higher cooldown if backing up messages and maybe auto delete the backups (made by interval) after 2 weeks or so

**Comment by jakester620** [comment]
That would be a perfect solution for that. Just set a minimum interval time
that's higher than normal and auto purge old ones. Even a week old or less.
