### ISSUE TITLE
Dm at the end of backup création

### ISSUE THREAD

**Issue by Mr-KayJayDee** [Magic-Bots/xenon#34]
An embed with the serveur name and others info at thé end of backup création because we have a command and a code but we do not know what it is and when we have several we get lost

**Comment by ThatLifeofGames** [comment]
Try that in English

**Comment by ThatLifeofGames** [comment]
If you are being understood correctly, xenon already does this, if not then feel free to respond with something that makes more sense.

**Comment by Mr-KayJayDee** [comment]
Sorry im french this is what i cant explain my idea

**Comment by merlinfuchs** [comment]
Use google translator :)

**Comment by Mr-KayJayDee** [comment]
This is what i do but it is not good

**Comment by withmask** [comment]
Bonjour, je remarque que vous êtes français et vous avez quelque problème avec le bot Xenon
A ce que j'ai pu comprendre tu ne reçoit pas de message quand une backup est créer ?
Si oui je te propose de rejoindre le serveur (https://discord.gg/4tMTQ6) on pourra t'aider mieux et comprendre ton problème
