### ISSUE TITLE
template list

### ISSUE THREAD

**Issue by cblastin** [Magic-Bots/xenon#35]
Instead of the **_x!template list_** command just pointing to the lists in the server, it should show ones you made yourself. Then at the bottom, have it point to the lists in the server. 

But, it'd be far more user friendly than the user just having to search for their own name in the server in case they forgot their own named templates, etc..

**Comment by ThatLifeofGames** [comment]
Could've added this to the template suggestions issue.

**Comment by cblastin** [comment]
listen, you're right. But, reeee I was lazy ok

**Comment by ThatLifeofGames** [comment]
Demoted

**Comment by merlinfuchs** [comment]
I think even more people would misunderstand the templates if I 'prioritize' their templates in the command.

**Comment by merlinfuchs** [comment]
#29
