### ISSUE TITLE
Template suggestion in Xenon Discord Server

### ISSUE THREAD

**Issue by Mennoplays** [Magic-Bots/xenon#36]
Hi there. Maybe is it nice to add in the embed in #template_list how much the template has been used.  I think you can collect the things by collecting the amount of templates loading commands. Every time that will happen, the bot will update the count in #template_list.

Greeting, Menno

**Comment by cblastin** [comment]
That would be a somewhat good feature for featured templates. But there's too many templates in #template_list for that feature to go well in the way you think it'll go.

Try to keep template suggestions [here](https://github.com/Magic-Bots/xenon/issues/29) for now on.

**Comment by Mennoplays** [comment]
> That would be a somewhat good feature for featured templates. But there's too many templates in #template_list for that feature to go well in the way you think it'll go.

I think it is useful, for people who are making a template of their discord server that they can see if people are using the templates.

**Comment by buthed010203** [comment]
Something like this would be good when templates move to the site.

**Comment by cblastin** [comment]
_If_ they move. Templates on the website haven't been fully decided yet or not.
