### ISSUE TITLE
x?backup reinvite should skip unreachable users before, and not after choosing 100 users to reinvite

### ISSUE THREAD

**Issue by sonofevil** [Magic-Bots/xenon#37]
When using the reinvite feature, Xenon seems to do the following steps:

1. choose the 100 users with the most roles from the backup
2. check which of those can be reached via DM
3. invite those users

In my case this yielded only 35 invites, and most of those invites seemed to go to users who were already in the server at that point. Kind of pointless.

In my humble opinion it should proceed in this way instead:

1. check which of the users in the backup aren't already in the new server
2. check which of those users can be reached via DM
3. out of these users select the 100 with the most roles
4. invite those users

This would be much more useful for a 500 user backup like mine. Presumably it would actually end up inviting 100 users who aren't currently in the server, which would be the behavior I had hoped for when signing up for Xenon pro.

**Comment by merlinfuchs** [comment]
Definitely a good idea! 👍

**Comment by merlinfuchs** [comment]
done
