### ISSUE TITLE
Allow export of backup to file(s) (especially userlist)

### ISSUE THREAD

**Issue by sonofevil** [Magic-Bots/xenon#38]
Title says it all.

Being able to download a plaintext file with the backed up list of users (names & IDs) would be pretty great.

Being able to import such files would also be cool, tho not something I personally need.

**Comment by cblastin** [comment]
Storing users usernames is against TOS so the best we'd even be able to do is store the ids.

**Comment by sonofevil** [comment]
> Storing users usernames is against TOS so the best we'd even be able to do is store the ids.

I see. Well, still something I could definitely use.

**Comment by merlinfuchs** [comment]
Xenon Pro provides a list of members in the info command
