### ISSUE TITLE
Disable pings in channel message sync

### ISSUE THREAD

**Issue by ThatLifeofGames** [Magic-Bots/xenon#40]
It can be really annoying to get pinged in two channels at once using the message sync, you could make it so the synced message doesn't actually ping the user as you only need to see it in one channel anyway.

Maybe don't do this by default, but have an option to.

**Comment by buthed010203** [comment]
Kinda related but not really but this would be nice when loading messages with x?copy/backup loading

**Comment by smokeofc** [comment]
This would be a really neat feature, especially if it could be set in the copy/backup command while invoking it. Like 'x?copy messages <ID> noping' or something like so
