### ISSUE TITLE
Bot is not starting

### ISSUE THREAD

**Issue by shadowplay1** [Magic-Bots/xenon#45]
![sdf](https://user-images.githubusercontent.com/43500997/58048687-cb033d80-7b53-11e9-823f-bb5d34b588b9.png)
How to fix this FUCKING error?! All directories there are, but I still can't run the bot! Please, help me. (if I am dumb, sorry)

**Comment by merlinfuchs** [comment]
Are you using docker?

**Comment by shadowplay1** [comment]
Yes

**Comment by merlinfuchs** [comment]
Did you create the logs directory?

**Comment by shadowplay1** [comment]
yes

**Comment by merlinfuchs** [comment]
Did you build / rebuild the container after creating the logs directory?
