### ISSUE TITLE
just started hosting the bot and i have some small questions

### ISSUE THREAD

**Issue by ShadowBallz** [Magic-Bots/xenon#46]
Where are the "backups" stored and how do i download them (commands guide please)
what database is this stored under and how do i access it??

sorry for wasting any time and thanks for any help

**Comment by merlinfuchs** [comment]
It's stored in a mongodb that is running in the docker container. You can access the data over [mongodb compass](https://www.mongodb.com/products/compass). 

But you need to add this to the docker-compose.yml file below the 
```yml
expose:
     - "27017"
```
 statement to be able to access the database.
```yml
ports:
     - "27017"
```

**Comment by ShadowBallz** [comment]
Thank you, I assume xenon pro is private to prevent ppl from using the pro commands for free?

**Comment by merlinfuchs** [comment]
Yes

**Comment by ShadowBallz** [comment]
i added the ports thing but it did not work 
https://i.imgur.com/lJE5x4n.png
do i need to type anything special to access it
https://i.imgur.com/3lA768X.png

**Comment by merlinfuchs** [comment]
Nah, just click on connect. There should be a database called xenon.

**Comment by ShadowBallz** [comment]
Clicking connect doesn't show the database (maybe because I have "monogod" running) when I turn that off and try to connect I get the "no database is running on the host"message 

I used docker to host the thing and added the ports thing at the bottom

**Comment by merlinfuchs** [comment]
You obviously need to connect to the database in the container and not one that you are running manually.
Did you restart the container after editing the docker-compose file?

**Comment by ShadowBallz** [comment]
Restarted the container and it all works fine 👌 can I see where the bans are stored?

**Comment by merlinfuchs** [comment]
The backups including the bans are stored in the backups collection.
