### ISSUE TITLE
Make it clear that this is not a message backup bot

### ISSUE THREAD

**Issue by mutmedia** [Magic-Bots/xenon#47]
I just deleted all the messages in my server, after one admin of it made the same mistake. At first I thought he was stupid because he didn't read instructions, so I went to use the bot myself, with the following flow:

![image](https://user-images.githubusercontent.com/4412564/60984770-1aaeeb80-a2f1-11e9-94c8-c7c75352a598.png)

![image](https://user-images.githubusercontent.com/4412564/60984803-27cbda80-a2f1-11e9-9497-5e8e6adc6c03.png)

![image](https://user-images.githubusercontent.com/4412564/60984887-48943000-a2f1-11e9-881a-04f9d405a575.png)

Notice that at any point it was ever clearly mentioned that the bot would wipe out all the messages in my server*

I still though that I was doing something wrong so I looked for the bot page, where I found this:

![image](https://user-images.githubusercontent.com/4412564/60985528-80e83e00-a2f2-11e9-8396-65f2d2bb346a.png)

Only then did I find this:

![image](https://user-images.githubusercontent.com/4412564/60985672-b7be5400-a2f2-11e9-8c7d-73d644c5e173.png)

Which is the first place that explicitly mentions that the bot only saves messages for the pro version, and still only 25. I understand that actually backing up all the messages can be very hard to do. However, I think what happened to me could've been prevented with clearer messages and better explanation of what the bot actually does.

I'm suggesting making it very clear on the front page that only the PRO version does the backup of messages (and would go a step further mentioning the 25 message limit, so people don't pay and lose their messages)

*: Only after knowing that clearing the server is the expected behaviour that I understood what "your channels will be replaced meant", this could be much more clearer message, such as "all your messages in all your channels will be deleted", since losing all the messages might be a very critical problem for some servers, especially ones that was just looking for a tool to back them up.

**Comment by merlinfuchs** [comment]
It should be pretty obvious that deleting all channels also means deleting all messages in the channels.
Anyways, I will try to make it clearer in the documentation and edit the warning.
Thanks for bringing this issue up.

**Comment by mutmedia** [comment]
There is no point where the word **deleted** was being used, if it were, it might've been clearer, but still it doesn't hurt to make things even more obvious by excplicitly mentioning the consequences.

**Comment by mutmedia** [comment]
Also I think you should learn a bit more about treating your users. I've seen some other instances of that on the discord channel where you say something is obvious, implying any consequences of the misuse of your product being on the stupidity of your user base.

You have to design assuming your user is a stupid person, that won't know how to use your product, being mad about them being stupid and blaming them for not using your product properly is the actual only stupid behaviour here.

I would highly recommend reading the chapter on **mistakes and slips** on the book [The Design of everyday things](https://www.amazon.com/Design-Everyday-Things-Revised-Expanded-ebook/dp/B00E257T6C/ref=tmm_kin_swatch_0?_encoding=UTF8&qid=&sr=)

**Comment by merlinfuchs** [comment]
Thanks for your feedback :)
