### ISSUE TITLE
Copy without deleting

### ISSUE THREAD

**Issue by Heavenlyt** [Magic-Bots/xenon#48]
When you copy/load a backup of a server it deletes everything that is on it, it would be nice to have an option where you can choose to keep the roles or choose to keep the channels instead of deleting everything.

**Comment by ThatLifeofGames** [comment]
Do you mean something like issue #3

**Comment by Heavenlyt** [comment]
Not really, I'm saying more like merging backups/adding roles from one backup to another.

**Comment by merlinfuchs** [comment]
What about channel specific permissions?

**Comment by Heavenlyt** [comment]
You could make it so you can choose whether to keep or delete the permissions when merging/creating etc.

**Comment by merlinfuchs** [comment]
If you merge the roles from server a with the channels from server b, there is no way to keep the channel specific permissions.

**Comment by Heavenlyt** [comment]
That's fine then I guess, would be nice to just have the option to combine the roles instead of everythign else. Example, if you have a backup with color roles and want to put that onto another server, it deletes all the channels & roles from that server and replaces it with the colours and no channels.
