### ISSUE TITLE
Pro sync problems when syncing to more than one channel

### ISSUE THREAD

**Issue by smokeofc** [Magic-Bots/xenon#49]
I have access to 3 servers where I've invited pro. more or less like so

Server 1:
Channel 1.1
Server 2:
Channel 2.1
Server 3:
Channel 3.1

Now, I want to sync channel 1.1 to 2.1 and 3.1, so I run "x?sync messages <channel 1.1 ID>" in Channels 2.1 and 3.1 in that order.

The result is that sync of text goes just as it should in 2.1, but in 3.1 it posts synced images twice.  If I test on a third channel, it posts it three times. I have not tried any further, but it seems it's likely it'll post four times in the forth channel etc

**Comment by merlinfuchs** [comment]
Are we talking about attached images or image links?
Please provide some screenshots

**Comment by smokeofc** [comment]
![laugh](https://user-images.githubusercontent.com/13959015/61965942-be76e780-afd1-11e9-9e0c-74b841001508.png)
This is channel 3-1 in the example above
As you can see, the one thing that were said on the test server only synced over once, the images is another story entirely though

**Comment by smokeofc** [comment]
Is there any movement on this, or any more information needed for resolving this?

**Comment by merlinfuchs** [comment]
I found the issue and fixed it. It's not pushed yet tho.
