### ISSUE TITLE
Reinvite more members by skipping the already invited ones

### ISSUE THREAD

**Issue by Mikaru0Mystic** [Magic-Bots/xenon#52]
Hi i wanted to recommend something, is it possible for the reinvite thing to like... log who it invited already and skip them like if it gets triggered again in a period? Like, they cant be reinvited in the same day. So we can reinvite all a srver slowly in an easier way. Or like make an option to skip them.

**Comment by merlinfuchs** [comment]
Reinvite feature no longer exists
