### ISSUE TITLE
Make the bot can backup your all server messages?

### ISSUE THREAD

**Issue by Matsko3** [Magic-Bots/xenon#53]
What about make the bot can backup your all server messages just like if you have many messages in your server and you don't want to lose it then you can backup and not lose it i think that would be helpful for me and people.

**Comment by ThatLifeofGames** [comment]
.. If it was possible do you not think it would already be an option?

Before opening requests like this I highly suggest you talk about it in the support server first.

And also maybe try a new translation service (or read stuff before you post it?)
