### ISSUE TITLE
Allow multiple backups to be kept on interval (pro/turbo?)

### ISSUE THREAD

**Issue by ThatLifeofGames** [Magic-Bots/xenon#60]
Let the backup interval keep multiple backups (maybe up to 3) as if something happens to a server, and it creates a backup after it happens, you have no useful interval backup (if that doesn't make sense, ask).

The IDs could simply be something like guildid-number (eg 410488579140354049**-2**)

**Comment by merlinfuchs** [comment]
Maybe for pro and turbo.

**Comment by niansa** [comment]
I would look at solving this, but I am not sure because... Well if it's for pro/turbo it probably won't get accepted because pull requests are public right?
