### ISSUE TITLE
Syncing files

### ISSUE THREAD

**Issue by smokeofc** [Magic-Bots/xenon#67]
When syncing a uploaded file, Xenon just leaves an empty box in the target chat. Would it be possible to have it instead include the link to that file? Or some other manner to sync that gives access to that file in the target server as well?

![sync](https://user-images.githubusercontent.com/13959015/64968046-cbada580-d8a1-11e9-87ee-a704edfcb1a8.png)

**Comment by merlinfuchs** [comment]
Should be fixed
