### ISSUE TITLE
Xenon Turbo Backup/Copying Out of Order

### ISSUE THREAD

**Issue by wolfdragon91** [Magic-Bots/xenon#70]
I'm a bit frustrated because I've been using Xenon to backup my server, and I've been using another one designated as my backup. I was using Xenon Pro, but I needed more than 25 messages, so I upgraded to Xenon Turbo and was using that. But when I try to Backup and load into the other server, copy over, copy messages, etc., the messages seem to occasionally be out of order, and usually it is one of the first few messages that is out of order (the oldest posts), and often in the same spots (but not always). Some of them have over 50 messages, but they're things like rules which I can't have out of order causing confusion. As far as I know, it's only Xenon Turbo doing this, but the other Xenons would not have the power to copy over 25 messages anyway. Please, if anything can be done. I'll try to post a picture...

**Comment by wolfdragon91** [comment]
<img width="1920" alt="XTOOOBackMess0" src="https://user-images.githubusercontent.com/55676738/65400014-cf539780-dd8d-11e9-97d6-0c0bcec9a346.png">
<img width="1920" alt="XTOOOBackMess1" src="https://user-images.githubusercontent.com/55676738/65400018-d37fb500-dd8d-11e9-99fb-5c8efc61c5b9.png">

**Comment by merlinfuchs** [comment]
This is caused by discord responding to my request before actually sending the message. 

I will add an option that fixes this, but that will slow down the loading process.

**Comment by merlinfuchs** [comment]
The option is called "safe", you can use it like this:

```
x:backup load <backup-id> 250 safe
```
(250 representing the count of messages to load)

**Comment by wolfdragon91** [comment]
Okay, I'll create a new backup then try it on the backup server. I'll inspect it for any out of order posts again.

**Comment by wolfdragon91** [comment]
Okay, I tried to look out for anything else, it's a bit tedious to check super thoroughly so it's possible there may be things missed. However, I checked what I noticed a lot of the problem areas were before and everything seems good now.

What I did was " x:backup create 250 safe " then loaded "x:backup load [backup-id] 250 safe" on the backup server and everything seems good now. It was also still fast (I didn't notice a difference in speed from before). Thank you! That saves the huge hassle of trying to fix it manually or using an alternative.

Now I suspect the "x:backup create [number] safe" was unnecessary (I was unsure). So I'd like to ask, when/how are you supposed to use "safe"? Like does it also work with "x:copy [guild id] [number]" and "x:copy messages [channel id] [number]" as well? And will this always be necessary or is this going to change?

**Comment by merlinfuchs** [comment]
It's part of the loading options (https://docs.discord.club/xenon/how-to/backups#loading-a-backup). There is currently no option like that for copying, but I might just make it the default for all commands, because the speed difference isn't that big.

**Comment by wolfdragon91** [comment]
Okay. Thank you! I'm reasonably satisfied and will let you know if any other problems come up in the future. I'll continue using "safe" unless notified this changes in the future (I'll keep an eye on places like the website and the discord channel). I'm not sure if you want me to close this issue or not, so I'll leave that up to you. Thanks again! :)

**Comment by merlinfuchs** [comment]
No Problem :)
