### ISSUE TITLE
Allow load options for templates

### ISSUE THREAD

**Issue by ThatLifeofGames** [Magic-Bots/xenon#77]
Backups have load options (for example loading roles only) but templates don't.

Sometimes people only want the roles/channels from a template so it may be useful to add this to templates.

**Comment by merlinfuchs** [comment]
https://github.com/Magic-Bots/xenon/commit/2a2d3e15a6fcd9801fb828dd8a4b5aac79451cbb

**Comment by ThatLifeofGames** [comment]
_oh_
