### ISSUE TITLE
Stored Nicknames

### ISSUE THREAD

**Issue by merlinfuchs** [Magic-Bots/xenon#8]
In addition to the already saved data. Could we get an implementation of nicknames being saved as well? It would be a godsend for a server with a large population such as ours, 28k+.

https://gitlab.com/magicbots/xenon_pu/issues/5

**Comment by buthed010203** [comment]
Arent nicknames already saved though? lol

**Comment by merlinfuchs** [comment]
Saved yes, but they don't get loaded

**Comment by buthed010203** [comment]
They do whenever I load a backup :p

**Comment by buthed010203** [comment]
Might just load a few of em then like with bans

**Comment by merlinfuchs** [comment]
Can be combined with the assigned roles in one request per member

**Comment by merlinfuchs** [comment]
Merlintor/discord-backups@d1e2524
