### ISSUE TITLE
Role issues

### ISSUE THREAD

**Issue by ShikamiRyuk** [Magic-Bots/xenon#82]
Good afternoon, i been having a issue with xenon where if i load a backup the bot will hand out random roles to random people, sometimes even admin/owner roles wich have a lot of permissions that i don't want people to have... It happened 2x now a few days ago. Is there any way this would be fixed? Got told in the support discord to create a post here. Hope that it can be solved and if you need any additional information contact me trough email rovecurse@gmail.com

**Comment by merlinfuchs** [comment]
The bot removes all permissions from the roles before assigning them. It sets the correct permissions after assigning all roles. Did the bot set the role permissions correctly?

**Comment by ShikamiRyuk** [comment]
Yes the permissions where set fine, just members got the admin and even the owner roles wich have more permissions then a member role, people had all kinds of random roles they never had wich caused a lot of issues.

**Comment by merlinfuchs** [comment]
Is the Xenon role above all other assignable roles?

**Comment by merlinfuchs** [comment]
And are the permissions overwrites (channel specific permissions) set correctly?

**Comment by ShikamiRyuk** [comment]
Yes the xenon role is above all assignable ones, the channels never had a issue it's just the roles it gave the people where all wrong for the rest it did everything perfectly

**Comment by merlinfuchs** [comment]
Are you sure that the permissions overwrites are correct?

**Comment by ShikamiRyuk** [comment]
What do you mean with permission overwrites? The channel permissions it put the server back with?

**Comment by merlinfuchs** [comment]
The channel specific permissions. e.g:
![image](https://user-images.githubusercontent.com/33966852/66594820-23d28180-eb9a-11e9-827d-b75a06b88ae4.png)

**Comment by ShikamiRyuk** [comment]
Yes they are all correct

**Comment by ShikamiRyuk** [comment]
We double checked all categories after we roled back since we seen all roles where messed up we thought that the channels might where to

**Comment by merlinfuchs** [comment]
I neither can reproduce this nor do I know anything that could cause this.
Can you try to load the backup again (maybe on a different server) and check if the bug persists? Please send me an invite if it does.

**Comment by ShikamiRyuk** [comment]
I will make another server and then try to redo it, i cannot to it on my current one because it hurts our members and is a lot of work to fix

**Comment by merlinfuchs** [comment]
Yeah, I understand that. You will need some members tho, so the bot can try to assign the roles.
Thanks for the effort.

**Comment by ShikamiRyuk** [comment]
Let's see if it does it again, it did it twice in a row to my main server. https://discord.gg/XZNXWx
